---
- name: "sec03 | sec03-main | Check OS family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu. {{ ansible_facts.distribution }} is not supported."
  when:
    - ansible_facts.distribution != 'Ubuntu'
  tags:
    - always

- name: "sec03 | sec03-main | Check OS version and family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: "sec03 | sec03-main | Import subsection 01 - Configure Network Devices"
  ansible.builtin.import_tasks:
    file: sec03/sec03-01.yml
  when: hardening_sec03_01
  tags:
    - always

- name: "sec03 | sec03-main | Import subsection 02 - Configure Network Kernel Modules"
  ansible.builtin.import_tasks:
    file: sec03/sec03-02.yml
  when: hardening_sec03_02
  tags:
    - always

- name: "sec03 | sec03-main | Import subsection 03 - Configure Network Kernel Parameters"
  ansible.builtin.import_tasks:
    file: sec03/sec03-03.yml
  when: hardening_sec03_03
  tags:
    - always

...
