---
- name: "sec03 | sec03-01 | Check OS family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu. {{ ansible_facts.distribution }} is not supported."
  when:
    - ansible_facts.distribution != 'Ubuntu'
  tags:
    - always

- name: "sec03 | sec03-01 | Check OS version and family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: "sec03 | sec03-01 | Disable IPv6 (net.ipv6.conf.all.disable_ipv6)"
  ansible.builtin.lineinfile:
    path: "{{ hardening_disable_ipv6_conf_path }}"
    regexp: '^net\.ipv6\.conf\.all\.disable_ipv6\s'
    line: net.ipv6.conf.all.disable_ipv6 = 1
    mode: '0644'
    owner: root
    group: root
    create: true
  when:
    - hardening_disable_ipv6
  notify:
    - Apply network settings
    - Restart procps
  tags:
    - always

- name: "sec03 | sec03-01 | Disable IPv6 (net.ipv6.conf.default.disable_ipv6)"
  ansible.builtin.lineinfile:
    path: "{{ hardening_disable_ipv6_conf_path }}"
    regexp: '^net\.ipv6\.conf\.default\.disable_ipv6\s'
    line: net.ipv6.conf.default.disable_ipv6 = 1
    mode: '0644'
    owner: root
    group: root
    create: true
  when:
    - hardening_disable_ipv6
  notify:
    - Apply network settings
    - Restart procps
  tags:
    - always

- name: "sec03 | sec03-01 | Disable IPv6 (net.ipv6.conf.lo.disable_ipv6)"
  ansible.builtin.lineinfile:
    path: "{{ hardening_disable_ipv6_conf_path }}"
    regexp: '^net\.ipv6\.conf\.lo\.disable_ipv6\s'
    line: net.ipv6.conf.lo.disable_ipv6 = 1
    mode: '0644'
    owner: root
    group: root
    create: true
  when:
    - hardening_disable_ipv6
  notify:
    - Apply network settings
    - Restart procps
  tags:
    - always

- name: "sec03 | sec03-01 | Enable IPv6 (net.ipv6.conf.all.disable_ipv6)"
  ansible.builtin.lineinfile:
    path: "{{ hardening_disable_ipv6_conf_path }}"
    regexp: '^net\.ipv6\.conf\.all\.disable_ipv6\s'
    line: net.ipv6.conf.all.disable_ipv6 = 0
    mode: '0644'
    owner: root
    group: root
    create: true
  when:
    - not hardening_disable_ipv6
  notify:
    - Apply network settings
    - Restart procps
  tags:
    - always

- name: "sec03 | sec03-01 | Enable IPv6 (net.ipv6.conf.default.disable_ipv6)"
  ansible.builtin.lineinfile:
    path: "{{ hardening_disable_ipv6_conf_path }}"
    regexp: '^net\.ipv6\.conf\.default\.disable_ipv6\s'
    line: net.ipv6.conf.default.disable_ipv6 = 0
    mode: '0644'
    owner: root
    group: root
    create: true
  when:
    - not hardening_disable_ipv6
  notify:
    - Apply network settings
    - Restart procps
  tags:
    - always

- name: "sec03 | sec03-01 | Enable IPv6 (net.ipv6.conf.lo.disable_ipv6)"
  ansible.builtin.lineinfile:
    path: "{{ hardening_disable_ipv6_conf_path }}"
    regexp: '^net\.ipv6\.conf\.lo\.disable_ipv6\s'
    line: net.ipv6.conf.lo.disable_ipv6 = 0
    mode: '0644'
    owner: root
    group: root
    create: true
  when:
    - not hardening_disable_ipv6
  notify:
    - Apply network settings
    - Restart procps
  tags:
    - always

...
