---
- name: "sec02-03 | timesyncd | Remove chrony package"
  ansible.builtin.apt:
    name: "chrony"
    state: absent
  tags:
    - always

- name: "sec02-03 | timesyncd | Remove dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: true
    purge: true
  tags:
    - always

- name: "sec02-03 | timesyncd | Create target folder ({{ hardening_time_timesyncd_path | dirname }})"
  ansible.builtin.file:
    path: "{{ hardening_time_timesyncd_path | dirname }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - always

- name: "sec02-03 | timesyncd | Apply NTP settings ({{ hardening_time_timesyncd_path }})"
  ansible.builtin.template:
    src: sec02/sec02-03/timesyncd.conf.j2
    dest: "{{ hardening_time_timesyncd_path }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart systemd-timesyncd service
    - Restart cron service
    - Restart systemd-journald service
  tags:
    - always

...
