---
# handlers file for ubuntu24-cis
- name: Restart cron.service
  ansible.builtin.systemd_service:
    name: cron.service
    state: restarted
    enabled: true
    masked: false
  tags:
    - always

- name: Restart systemd-timesyncd.service
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    state: restarted
    enabled: true
    masked: false
  tags:
    - always

- name: Restart systemd-journald.service
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted
    enabled: true
    masked: false
  tags:
    - always

- name: Restart chronyd.service
  ansible.builtin.systemd_service:
    name: chronyd.service
    state: restarted
    enabled: true
    masked: false
  tags:
    - always

- name: Update AIDE database
  ansible.builtin.copy:
    src: /var/lib/aide/aide.db.new
    dest: /var/lib/aide/aide.db
    owner: root
    group: root
    mode: '0644'
    remote_src: true
  tags:
    - always

- name: Restart postfix.service
  ansible.builtin.systemd_service:
    name: postfix.service
    state: restarted
    enabled: true
    masked: false
  tags:
    - always

- name: Apply network settings
  ansible.builtin.command: sysctl -p
  register: apply_network
  changed_when: true
  failed_when: false
  tags:
    - always

- name: Restart procps
  ansible.builtin.systemd_service:
    name: procps
    state: restarted
    enabled: true
    masked: false
  tags:
    - always

- name: Grub update
  ansible.builtin.command: update-grub
  changed_when: true
  failed_when: false
  tags:
    - always

...
