---
- name: "sec01 | sec01-02 | Check OS family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu. {{ ansible_facts.distribution }} is not supported."
  when:
    - ansible_facts.distribution != 'Ubuntu'
  tags:
    - always

- name: "sec01 | sec01-02 | Check OS version and family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: "sec01 | sec01-02 | Run update_cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ updates_cache_valid_time }}"
  tags:
    - always

- name: "sec01 | sec01-02 | Update all packages to their latest version"
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  when: hardening_upgrade_installed_packages
  tags:
    - always

- name: "sec01 | sec01-02 | Remove useless packages from the cache"
  ansible.builtin.apt:
    autoclean: true
  tags:
    - always

- name: "sec01 | sec01-02 | Remove dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: true
    purge: "{{ hardening_updates_autoremove_purge }}"
  tags:
    - always

...
