---
- name: "sec04 | sec04-main | Check OS family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu. {{ ansible_facts.distribution }} is not supported."
  when:
    - ansible_facts.distribution != 'Ubuntu'
  tags:
    - always

- name: "sec04 | sec04-main | Check OS version and family"
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: "sec04 | sec04-main | Import subsection 02 - Configure Uncomplicated Firewall"
  ansible.builtin.import_tasks:
    file: sec04/sec04-02.yml
  when: hardening_sec04_02
  tags:
    - always

- name: "sec04 | sec04-main | Import subsection 03 - Configure nftables"
  ansible.builtin.import_tasks:
    file: sec04/sec04-03.yml
  when: hardening_sec04_03
  tags:
    - always

- name: "sec04 | sec04-main | Import subsection 04 - Configure iptables"
  ansible.builtin.import_tasks:
    file: sec04/sec04-04.yml
  when: hardening_sec04_04
  tags:
    - always

...
